apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-config-client
  name: demo-config-client
  namespace: demo-config-ns
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-config-client
status:
  loadBalancer: {}
